person:
  age: 10
  sex: 男
  name: 杜琛明
server:
  servlet:
    encoding:
      force-response: true
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 40960MB
      max-request-size: 40960MB
      resolve-lazily: false
