person:
  age: 10
  sex: 男
  name: 杜琛明
server:
  servlet:
    encoding:
      force-response: true
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 2MB
      max-request-size: 2MB
      resolve-lazily: false
